# Task 1: Netflix Data Cleaning & Preparation

**Internship:** Data Analysis Using Python  
**Organization:** Auspify Technologies  
**Intern:** Yash Lawaniya

## Project Overview

This project focuses on cleaning and preparing the Netflix dataset for further analysis and business reporting. The work includes inspecting the dataset, checking missing values and duplicate records, converting the date column into datetime format, standardizing duration information, validating the cleaned data, and exporting the final dataset.

## Objectives

- Load and inspect the Netflix dataset using Pandas.
- Examine the dataset's structure, columns, and data types.
- Identify missing values and calculate their percentages.
- Detect exact duplicate records.
- Convert the `date_added` column into datetime format.
- Separate duration values and units into individual columns.
- Validate the cleaned dataset.
- Export the cleaned dataset for future analysis.

## Technologies Used

- **Python:** Programming language used for data analysis.
- **Pandas:** Data manipulation, inspection, and cleaning.
- **NumPy:** Numerical operations where required.
- **Jupyter Notebook:** Interactive coding and documentation.

## Project Workflow

- Import the required libraries.
- Load and inspect the original dataset.
- Analyze missing values and duplicate records.
- Inspect and convert the date column.
- Extract and standardize duration values and units.
- Perform final data-quality checks.
- Save the cleaned dataset as a CSV file.

## Dataset Information

The original dataset is stored in CSV format and loaded into a Pandas DataFrame. The cleaning process preserves the original duration information while adding separate columns for numeric duration values and their corresponding units.

The cleaned dataset is exported to `data/processed/netflix_cleaned.csv` for use in subsequent analysis.

In [1]:
# Task 1: Netflix Data Cleaning & Preparation
# Intern: Yash Lawaniya
# Organization: Auspify Technologies

import pandas as pd
import numpy as np

print("Libraries imported successfully!")

Libraries imported successfully!

## Step 1: Load the Dataset

The original Netflix dataset is stored in CSV format. We use the Pandas `read_csv()` function to load the file into a DataFrame, which allows us to inspect and manipulate its rows and columns.

The original dataset will be preserved, and any cleaned output will be saved separately.

In [2]:
# Load the original Netflix dataset

file_path = "../../data/raw/Dataset.csv"

df = pd.read_csv(file_path)

print("Dataset loaded successfully!")
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Dataset loaded successfully!
Number of rows: 8790
Number of columns: 10

## Step 2: Inspect the Dataset

Before modifying the data, we examine its structure and contents.

- `df.head()` displays the first five records to provide an initial view of the dataset.
- `df.info()` displays column names, data types, non-null counts, and memory usage.

This inspection helps us understand the dataset and identify areas that may require cleaning.

In [3]:
# Display the first five rows

df.head()

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"

In [4]:
# Inspect column names, data types, and non-null values

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8790 entries, 0 to 8789
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8790 non-null   str
 1   type          8790 non-null   str
 2   title         8790 non-null   str
 3   director      8790 non-null   str
 4   country       8790 non-null   str
 5   date_added    8790 non-null   str
 6   release_year  8790 non-null   int64
 7   rating        8790 non-null   str
 8   duration      8790 non-null   str
 9   listed_in     8790 non-null   str
dtypes: int64(1), str(9)
memory usage: 686.8 KB

## Step 3: Missing Value Analysis

Missing values are records where one or more columns do not contain a value. These can affect the accuracy of analysis and reporting.

In this step, we calculate the number and percentage of missing values in each column. We will use the results to decide how to handle missing data without unnecessarily losing useful information.

In [5]:
# Check missing values in each column

#Count missing values in each column. 
missing_values = df.isnull().sum()

# Calculate missing value percentages. 
missing_percentage = (missing_values/len(df))*100

# Create a summary table with counts and percentages. 
missing_summary = pd.DataFrame({
    "Missing Values": missing_values,
    "Missing Percentage": missing_percentage
})

# Sort columns by missing value count, highest first. 
missing_summary = missing_summary.sort_values(
    by="Missing Values",
    ascending=False
)

missing_summary

              Missing Values  Missing Percentage
show_id                    0                 0.0
type                       0                 0.0
title                      0                 0.0
director                   0                 0.0
country                    0                 0.0
date_added                 0                 0.0
release_year               0                 0.0
rating                     0                 0.0
duration                   0                 0.0
listed_in                  0                 0.0

## Step 4: Duplicate Record Analysis

In [6]:
duplicate_count = df.duplicated().sum()
print("Number of duplicate rows:",duplicate_count)

Number of duplicate rows: 0

In [7]:
#Display the first 5 exact duplicate rows, if any. 
df[df.duplicated()].head()

Empty DataFrame
Columns: [show_id, type, title, director, country, date_added, release_year, rating, duration, listed_in]
Index: []

In [8]:

# Display the data type of each column
df.dtypes

show_id           str
type              str
title             str
director          str
country           str
date_added        str
release_year    int64
rating            str
duration          str
listed_in         str
dtype: object

## Step 5: Date Column Analysis

### Step 5.1: Inspecting the Date Column

The `date_added` column currently has a string data type. Before converting it, we will inspect sample values to understand their format and identify any unusual entries.

This check helps us decide how to convert the column safely without accidentally losing valid dates.

In [9]:
# Display the first 10 values in the date_added column
df["date_added"].head(10)

0    9/25/2021
1    9/24/2021
2    9/24/2021
3    9/22/2021
4    9/24/2021
5    9/24/2021
6    9/24/2021
7     5/1/2021
8    9/23/2021
9     5/1/2021
Name: date_added, dtype: str

### Step 5.2: Converting the Date Column

The `date_added` column currently stores dates as strings. We will convert it into Pandas datetime format using `pd.to_datetime()`.

This conversion will allow us to extract the year and month, sort dates chronologically, and perform time-based analysis more reliably.

In [10]:

# Step 5.2: Convert the date column

# Load the original dataset again
df = pd.read_csv("../../data/raw/Dataset.csv")

# Convert date_added into datetime format
df["date_added"] = pd.to_datetime(
    df["date_added"],
    format="%m/%d/%Y",
    errors="coerce"
)

# Display the first 10 converted dates
print("First 10 converted dates:")
print(df["date_added"].head(10))

# Check the column data type
print("\nData type:")
print(df["date_added"].dtype)

# Count dates that could not be converted
print("\nInvalid or missing dates:")
print(df["date_added"].isna().sum())

First 10 converted dates:
0   2021-09-25
1   2021-09-24
2   2021-09-24
3   2021-09-22
4   2021-09-24
5   2021-09-24
6   2021-09-24
7   2021-05-01
8   2021-09-23
9   2021-05-01
Name: date_added, dtype: datetime64[us]

Data type:
datetime64[us]

Invalid or missing dates:
0

## Step 6: Duration Column Analysis

In [11]:
#Display the first 10 duration values. 
print("First 10 duration values:")
print(df["duration"].head(10))

# Display the different duration units. 
print("\nDuration unit:")
print(df["duration"].str.extract(r"([A-Za-z]+)$")[0].value_counts())

First 10 duration values:
0       90 min
1     1 Season
2     1 Season
3       91 min
4      125 min
5    9 Seasons
6      104 min
7       87 min
8      127 min
9       76 min
Name: duration, dtype: str

Duration unit:
0
min        6126
Season     1791
Seasons     873
Name: count, dtype: int64

### Step 6.1: Standardizing Duration Information

The `duration` column contains numeric values combined with units. Movies generally use minutes, whereas TV Shows use seasons.

We will extract the numeric value and its unit into separate columns. This will make duration information easier to analyze while preserving the original column. The singular and plural season labels will also be standardized.

In [12]:
df["duration_value"] = pd.to_numeric(
    df["duration"].str.extract(r"(\d+)")[0],
    errors="coerce"
).astype("Int64")

df["duration_unit"] = df["duration"].str.extract(r"([A-Za-z]+)$")[0]

df["duration_unit"] = df["duration_unit"].replace(
    {"Seasons" : "Season"}
)

df[["type", "duration", "duration_value", "duration_unit"]].head(10)

      type   duration  duration_value duration_unit
0    Movie     90 min              90           min
1  TV Show   1 Season               1        Season
2  TV Show   1 Season               1        Season
3    Movie     91 min              91           min
4    Movie    125 min             125           min
5  TV Show  9 Seasons               9        Season
6    Movie    104 min             104           min
7    Movie     87 min              87           min
8    Movie    127 min             127           min
9    Movie     76 min              76           min

### Step 6.2: Checking Missing Duration Values

In this step, we will check whether any values are missing in the original `duration` column and the newly created duration columns.

In [13]:
df[["duration", "duration_value", "duration_unit"]].isnull().sum()

duration          0
duration_value    0
duration_unit     0
dtype: int64

In [14]:

# Check the duration units and their counts
df["duration_unit"].value_counts()

duration_unit
min       6126
Season    2664
Name: count, dtype: int64

In [15]:

# Check the number of rows and columns
df.shape

(8790, 12)

In [16]:
# Display all column names
df.columns

Index(['show_id', 'type', 'title', 'director', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'duration_value',
       'duration_unit'],
      dtype='str')

In [17]:

# Check missing values in all columns
df.isnull().sum()

show_id           0
type              0
title             0
director          0
country           0
date_added        0
release_year      0
rating            0
duration          0
listed_in         0
duration_value    0
duration_unit     0
dtype: int64

In [18]:

# Check for exact duplicate rows
df.duplicated().sum()

np.int64(0)

## Step 7: Saving the Cleaned Dataset

After completing the initial data-cleaning steps, we will save the cleaned dataset as a CSV file. This allows us to reuse the prepared data in future analysis without repeating the same cleaning steps.

In [19]:

# Save the cleaned dataset
df.to_csv("../../data/processed/netflix_cleaned.csv", index=False)